[package]
name = "pfs_rs"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.6"
glob = "0.3.2"
log = "0.4.22"
memmap2 = "0.9.5"
sha1 = "0.10.6"
walkdir = "2.5.0"
