[package]
name = "pfs_rs"
version = "0.1.4"
edition = "2024"

[profile.release]
lto = true
strip = true

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
env_logger = "0.11.8"
glob = "0.3.2"
log = "0.4.27"
memmap2 = "0.9.7"
sha1 = "0.10.6"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.20.0"
